# Generated by Django 3.0.2 on 2020-01-08 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='項目')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='説明')),
                ('item1', models.CharField(max_length=255, verbose_name='項目１')),
                ('item2', models.CharField(max_length=255, verbose_name='項目２')),
                ('item3', models.CharField(max_length=255, verbose_name='項目３')),
                ('item4', models.CharField(blank=True, max_length=255, verbose_name='項目４')),
                ('item5', models.CharField(blank=True, max_length=255, verbose_name='項目５')),
                ('item6', models.CharField(blank=True, max_length=255, verbose_name='項目６')),
                ('item7', models.CharField(blank=True, max_length=255, verbose_name='項目７')),
                ('item8', models.CharField(blank=True, max_length=255, verbose_name='項目８')),
                ('item9', models.CharField(blank=True, max_length=255, verbose_name='項目９')),
                ('item10', models.CharField(blank=True, max_length=255, verbose_name='項目１０')),
                ('item11', models.CharField(blank=True, max_length=255, verbose_name='項目１１')),
                ('item12', models.CharField(blank=True, max_length=255, verbose_name='項目１２')),
                ('item13', models.CharField(blank=True, max_length=255, verbose_name='項目１３')),
                ('item14', models.CharField(blank=True, max_length=255, verbose_name='項目１４')),
                ('item15', models.CharField(blank=True, max_length=255, verbose_name='項目１５')),
                ('item16', models.CharField(blank=True, max_length=255, verbose_name='項目１６')),
                ('item17', models.CharField(blank=True, max_length=255, verbose_name='項目１７')),
                ('item18', models.CharField(blank=True, max_length=255, verbose_name='項目１８')),
                ('item19', models.CharField(blank=True, max_length=255, verbose_name='項目１９')),
                ('item20', models.CharField(blank=True, max_length=255, verbose_name='項目２０')),
                ('item21', models.CharField(blank=True, max_length=255, verbose_name='項目２１')),
                ('item22', models.CharField(blank=True, max_length=255, verbose_name='項目２２')),
                ('item23', models.CharField(blank=True, max_length=255, verbose_name='項目２３')),
                ('item24', models.CharField(blank=True, max_length=255, verbose_name='項目２４')),
                ('item25', models.CharField(blank=True, max_length=255, verbose_name='項目２５')),
                ('item26', models.CharField(blank=True, max_length=255, verbose_name='項目２６')),
                ('item27', models.CharField(blank=True, max_length=255, verbose_name='項目２７')),
                ('item28', models.CharField(blank=True, max_length=255, verbose_name='項目２８')),
                ('item29', models.CharField(blank=True, max_length=255, verbose_name='項目２９')),
                ('item30', models.CharField(blank=True, max_length=255, verbose_name='項目３０')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ManyToManyField(blank=True, to='main_app.Category', verbose_name='カテゴリ')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='VoteQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='投票数')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Item', verbose_name='項目')),
                ('rankings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Ranking', verbose_name='ランキングID')),
            ],
            options={
                'db_table': 'vote_quantity',
            },
        ),
        migrations.CreateModel(
            name='VoteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Item', verbose_name='項目')),
                ('rankings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Ranking', verbose_name='ランキングID')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vote_history',
            },
        ),
    ]
